### ISSUE TITLE
Could not find the linking exemption on your copy of gpl.txt.

### ISSUE THREAD

**Issue by monoman** [benaston/NFeature#3]
Was that intended? If it had the exemption or was LGPL licensed I could think of using your library. 

As is, I'll probably have to write a similar library, or just use hardcoded feature toggles.

**Comment by monoman** [comment]
On the Nuget Gallery, the licensing points to LGPL, so perhaps it should just be fixed by committing the right license file in the source directory.

**Comment by benaston** [comment]
Hello Monoman,

Happy to change the license to the less restrictive LGPL. I'll make the commit and NuGet update when I get back from an errand I have to run. In the meantime, feel free to use under LGPL.

Best regards
Ben

**Comment by monoman** [comment]
OK. Thanks
